In [15]:
#1
pierwszej = c(11, 14, 8, 13, 19)
drugiej = c(4, 7, 14, 16, 17, 11)
#H0: czas nie zależy od grupy
#h1: czas zależy od grupy -> dla 2 grupy czas jest mniejszy druga < pierwsza: if( t1 >= t0)  {cnt ++} p.val = cnt/N
h = c(1,0,0,1,1,0,1,0,1,0,1) 

z=c(pierwszej,drugiej)
suma = sum(drugiej)
z
11+13+19+7+16+11
11,8,9

[1] 11 14  8 13 19  4  7 14 16 17 11

[1] 77

In [63]:
cs = 0.64
if (cs <= 0.5) p = 2*cs
if (cs > 0.5) p = 2-2*cs
p

[1] 0.72

In [21]:
X=c(75, 84, 82, 80,81) 
Y=c(92,93,87,87)

In [28]:
diff = function(samp ){
s= sort (samp)
l= length ( samp )
d =1:( l -1)
for (k in 2: l ){
d[k -1]= s [k]- s[k -1]
}
return (d)
}

aly=function(samp){
stat =0
l= length(samp)
for (k in 1: l)
stat = stat+k*(l +1 - k)* samp[k]
return (stat)
}


vartest = function ( samp1 , samp2 , NMonte ){
d1 = diff( samp1 )
d2 = diff( samp2 )
l= length(d1)
stat0 = aly(d1)
pd = d1
cnt =0
for (j in 1: NMonte ){
r=rbinom(l ,1 ,.5)
for (k in 1: l){
pd[k]= ifelse(r[ k], d1 [k], d2 [k ])
}
if( aly(pd) >= stat0) {cnt = cnt +1}
}
return ( cnt / NMonte ) #one - sided p- value
}

vartest (X,Y,1600)

ERROR: Error in if (aly(pd) >= stat0) {: brakuje wartości tam, gdzie wymagane jest TRUE/FALSE


In [36]:
x= c(11, 14, 8, 13)
y= c(4, 7, 14, 16, 17, 11)
N <- choose(length(x)+length(y), length(x))
# com <- combn(n+m, n)
# cnt <- 0
N
N <- choose(length(x)+length(y), length(y))
N

[1] 210

[1] 210

In [50]:
Z1<-c(3.3,5.2,7.3,9.4,4.5)
Z2<-c(3.4,3.7,4.8,5.4,3.9)
Z3<-c(4.6,7.2,3.6,4.5,6.3) 
Z4<-c(4.5,3.6,2.7,3.4,5.6) 

Z = as.data.frame(rbind(Z1,Z2,Z3,Z4))
NN <- get.knn(Z,3)
# block1 <- NN$nn.index[1:n, ]
# block2 <- NN$nn.index[(n+1):N, ]
NN


$nn.index
     [,1] [,2] [,3]
[1,]    2    3    4
[2,]    4    3    1
[3,]    4    2    1
[4,]    2    3    1

$nn.dist
         [,1]     [,2]     [,3]
[1,] 4.986983 6.828616 7.897468
[2,] 3.538361 4.658326 4.986983
[3,] 3.934463 4.658326 6.828616
[4,] 3.538361 3.934463 7.897468

V1  V2  V3  V4  V5 
Z1 3.3 5.2 7.3 9.4 4.5
Z2 3.4 3.7 4.8 5.4 3.9
Z3 4.6 7.2 3.6 4.5 6.3
Z4 4.5 3.6 2.7 3.4 5.6

In [ ]:
x = matrix(c(0.00, 2.21, 2.49, 1.78, 3.11, 2.94, 2.21, 0.00, 2.60, 3.27, 1.45, 3.29,2.49, 2.60, 0.00, 2.14, 0.43, 3.52,
           1.87, 3.27, 2.14, 0.00, 2.69, 2.60, 3.11, 1.45, 0.43, 2.69, 0.00, 3.48, 2.94, 3.29, 3.52, 2.60, 3.48, 0.00), byrow=TRUE, nrow = 6, ncol = 6)

ERROR: Error in block2[, 1:k]: niepoprawna liczba wymiarów


In [62]:
library(FNN)
library(RANN)

Z1<-c(0, 3.05, 2.33, 3.96, 2.01, 4.32, 2.62)
Z2<-c(3.05,0, 4.69, 3.29, 3.69, 5.44, 3.62)
Z3<-c(2.33, 4.69, 0, 3.99, 1.84, 2.96, 1.85)
Z4<-c(3.96, 3.29, 3.99, 0, 2.69, 3.12, 2.77)
Z5<-c(2.01, 3.69, 1.84, 2.69, 0, 2.77, 2.03)
Z6<-c(4.32, 5.44, 2.98, 3.12, 2.77, 0, 3.1)
Z7<-c(2.62, 3.62, 1.85, 2.77, 2.03, 3.1, 0)
Z = as.data.frame(rbind(Z1,Z2,Z3,Z4,Z5,Z6,Z7))
Z

NN <- get.knn(Z,k=ncol(Z)-1)
index = knn.index(Z,k=2)
index

T <- function(k,n,N ) {
  block1 <- NN$nn.index[1:n, ]
  block2 <- NN$nn.index [(n +1):N , ]
  i1 <- sum(block1[,1:k] <= n)  
  i2 <- sum(block2[,1:k] > n)
  return (1*sum(i1+i2)/(k*N))}

T2<- T(k=2,n=3,N=7)
T2 #0.5

V1   V2   V3   V4   V5   V6   V7  
Z1 0.00 3.05 2.33 3.96 2.01 4.32 2.62
Z2 3.05 0.00 4.69 3.29 3.69 5.44 3.62
Z3 2.33 4.69 0.00 3.99 1.84 2.96 1.85
Z4 3.96 3.29 3.99 0.00 2.69 3.12 2.77
Z5 2.01 3.69 1.84 2.69 0.00 2.77 2.03
Z6 4.32 5.44 2.98 3.12 2.77 0.00 3.10
Z7 2.62 3.62 1.85 2.77 2.03 3.10 0.00

[,1] [,2]
[1,] 5    3   
[2,] 1    4   
[3,] 7    5   
[4,] 7    5   
[5,] 7    3   
[6,] 3    4   
[7,] 5    3

[1] 0.5