In [18]:
H =        c(1, 0,  0, 1, 1,  0,1, 0, 1,  0, 1) 
wektor <- c(11,14, 8,13, 19, 4,7,14,16, 17, 11)
11+13+19+7+16+11

[1] 77

In [20]:
c = 0.64
if (c <= 0.5) p.val = 2*c
if (c > 0.5) p.val = 2-2*c
p.val

[1] 0.72

In [21]:
#Aly:
X = c(75, 84, 82, 80, 81)
Y = c(92, 93, 87, 87)

diff=function(samp){
s=sort(samp)
l=length(samp)
d=1:(l-1)
for(k in 2:l){
d[k-1]=s[k]-s[k-1]}
return(d)}

aly=function(samp){
stat=0
l=length(samp)
for(k in 1:l)
stat=stat+k*(l+1-k)*samp[k]
return(stat)}

amp = diff(X)
aly(amp)

[1] 40

In [29]:
N<-choose(4+6,6) 
N
N<-choose(4+6,4) 
N

[1] 210

[1] 210

In [24]:
library("mvtnorm")
my_sample = rmvnorm(n=100, mean=c(0,0), sigma=diag(2))
bootstrap <- function(N, my_sample){
  n <- length(my_sample)
  coeff <- numeric(N)
  for (i in 1:N) {
    x = sample(my_sample[,1], n, replace = TRUE) #bootstrap parametryczny
    y = sample(my_sample[,2], n, replace = TRUE)
    coeff[i] = cor(x,y) }
  return (coeff)
}
cor_sequence = bootstrap(1000,my_sample)
coeff_mean = mean(cor_sequence) #średnia ze współczynników korelacji z losowanych danych
coeff_mean #0.001523495

quantile(cor_sequence, c(0.025,0.975))

[1] -0.000622073

2.5%      97.5% 
-0.1392366  0.1381454

# Zad 1

In [21]:
library(datasets)
data(iris)
library(boot)

In [18]:
head(iris)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa 
6 5.4          3.9         1.7          0.4         setosa

In [41]:
#1a) Dla ka»dego rodzaju (zmienna Species) osobno w oparciu o 200 prób bootstrapowych oszacuj ±redni¡ i median¦ daugo±ci paatka (zmienna Petal.Length).
column = iris$Petal.Length
n <- length(column)
N <- 200 #ile prób bootstrapowych
stat_srednia <- numeric(N) #średnia
stat_mediana <- numeric(N) #mediana
x <- numeric(n)

for (species in unique(iris$Species)) {
  subset = iris[iris$Species == species,]$Sepal.Length
    for (i in 1:N) {
      x = sample(subset, n, replace = TRUE)
      stat_srednia[i] = mean(x)
      stat_mediana[i] = median(x)}
            cat("\n---------", species, "----- \n")
            cat("Oszacowanie średniej: ",mean(stat_srednia), " \n")
#             cat("Prawdziwa średnia: ", mean(subset), "\n")
            cat("Oszacowanie mediany: ", mean(stat_mediana), " \n")}
#             cat("Prawdziwa mediana: ", median(subset), "\n") }


--------- setosa ----- 
Oszacowanie średniej:  5.00598  
Oszacowanie mediany:  5.0045  

--------- versicolor ----- 
Oszacowanie średniej:  5.933677  
Oszacowanie mediany:  5.8915  

--------- virginica ----- 
Oszacowanie średniej:  6.583147  
Oszacowanie mediany:  6.47625  


In [23]:
#1b)Wyznacz przedziały ufności boostrapowe
for (species in unique(iris$Species)) {
    print(species)
    subset = iris[iris$Species == species,]$Sepal.Length
    print("----MEAN---") 
    print(boott(subset, mean, v.nboott=200, VS=TRUE, perc=c (.10 ,.90))$confpoints) 
    print("---MEDIAN---")  
    print(boott(subset, median, v.nboott=200, VS=TRUE, perc=c (.10 ,.90))$confpoints)
    print("------------------------------") }
#On tutaj liczył quantile(medianaboot, probs=c(0.025, 0.975))

[1] "setosa"
[1] "----MEAN---"


ERROR: Error in boott(subset, mean, v.nboott = 200, VS = TRUE, perc = c(0.1, : nie udało się znaleźć funkcji 'boott'


In [20]:
zad1c <- function(N){
    stat_srednia <- numeric(N) #średnia
    stat_mediana <- numeric(N) #mediana

    for (species in unique(iris$Species)) {
      subset = iris[iris$Species == species,]$Sepal.Length
        n <- length(subset)
        x <- numeric(n)
        for (i in 1:N) {
          x = sample(subset, n, replace = TRUE)
          stat_srednia[i] = mean(x)
          stat_mediana[i] = median(x)}
                cat("\n---------", species, "----- \n")
                cat("Oszacowanie średniej: ",mean(stat_srednia), " \n")
#                 cat("Prawdziwa średnia: ", mean(subset), "\n")
                cat("Oszacowanie mediany: ", mean(stat_mediana), " \n")
#                 cat("Prawdziwa mediana: ", median(subset), "\n") 
                cat("--------Przedziały ufności------", "\n")
                print("----MEAN---") 
                print(boott(subset, mean, v.nboott=N, VS=TRUE, perc=c (.10 ,.90))$confpoints) 
                print("---MEDIAN---")  
                print(boott(subset, median, v.nboott=N, VS=TRUE, perc=c (.10 ,.90))$confpoints)
                print("------------------------------")  } }
zad1c(3000)


--------- setosa ----- 
Oszacowanie średniej:  5.006844  
Oszacowanie mediany:  5.0129  
--------Przedziały ufności------ 
[1] "----MEAN---"


ERROR: Error in boott(subset, mean, v.nboott = N, VS = TRUE, perc = c(0.1, 0.9)): nie udało się znaleźć funkcji 'boott'


# Zad 2 Czy liczba braków zmieniła się o 15%?

In [71]:
before <- c(12, 9, 21, 14, 7, 17) 
after <- c(5, 9, 3, 11, 8, 19) #Gdyby po było mniej, to każde wylosowanie elementów z before 
#dawałoby sumę większą
before <- 0.85*before
#Rozkład normalny był rozkładem ciągłym, a tutaj mamy skokowy
m<-length(before)
n<-length(after)
N<-choose(n+m,m) # liczba permutacji
suma=sum(after)
cnt =0 # licznik

z=c(before,after)
combin = combn((m+n),m) 
for (i in 1: N ){ 
    x1 <-z[combin[,i]]
    y1 <-z[-combin[,i]]
    if( sum (y1) <= suma ){ cnt = cnt +1}} #sum(x) >= suma. 
cs = cnt /N #p- wartość dla H0: Próbki nie różnią się

# #wilcoxona bo dane nieciągłe
# wilcoxorg = wilcox.test(before, after)$statistic #on tutaj użył mu=0.15 exact=F $statistic i c użył 2*c lub 2-2*c
# stat = numeric(n)
# options(warn = -1) 
# Permutation = choose(length(before)+length(after), length(before))
# combin = combn((length(before)+length(after)), length(before))
# for (i in 2:Permutation){
#   x1 <-z[combin[,i]]
#   y1 <-z[-combin[,i]]
#   wilcoxon_value = wilcox.test(x1,y1)$statistic 
#   if (wilcoxon_value >= wilcoxorg){ cnt=cnt+1 }}
# cnt/Permutation 
# cs = cnt/Permutation
if (cs <= 0.5) p = 2*cs
if (cs > 0.5) p = 2-2*cs
p

[1] 0.461039

In [69]:
x <- c(12, 9, 21, 14, 7, 17)
y <- c(5, 9, 3, 11, 8, 19)
x <- 0.85*x #
xy <- c(x,y)

n <- length(x)
m <- length(y)
N <- choose(n+m, n)
com <- combn(n+m, n)
cnt <- 0

stat <-  wilcox.test(x,y)$statistic 
for (i in 1:N)
{ x1 <- xy[com[, i]]
  y1 <- xy[-com[, i]]
  if(wilcox.test(x1,y1)$statistic<=stat)
  { cnt = cnt + 1 } }
cs = cnt/N
if (cs <= 0.5) p = 2*cs
if (cs > 0.5) p = 2-2*cs
p

[1] 0.3939394

# Zad 3 

In [87]:
x = matrix(c(0.00, 2.21, 2.49, 1.78, 3.11, 2.94, 2.21, 0.00, 2.60, 3.27, 1.45, 3.29,2.49, 2.60, 0.00, 2.14, 0.43, 3.52,
           1.87, 3.27, 2.14, 0.00, 2.69, 2.60, 3.11, 1.45, 0.43, 2.69, 0.00, 3.48, 2.94, 3.29, 3.52, 2.60, 3.48, 0.00), byrow=TRUE, nrow = 6, ncol = 6)
rownames(x) <- c("X1","X2","X3", "Y1", "Y2", "Y3") #6elementowy
colnames(x) <- c("X1","X2","X3", "Y1", "Y2", "Y3")
x 

X1   X2   X3   Y1   Y2   Y3  
X1 0.00 2.21 2.49 1.78 3.11 2.94
X2 2.21 0.00 2.60 3.27 1.45 3.29
X3 2.49 2.60 0.00 2.14 0.43 3.52
Y1 1.87 3.27 2.14 0.00 2.69 2.60
Y2 3.11 1.45 0.43 2.69 0.00 3.48
Y3 2.94 3.29 3.52 2.60 3.48 0.00

In [67]:
x <- matrix(rnorm(12), 3,4)
y <- matrix(rnorm(12), 3,4)
z <- rbind(x,y)
DATA <- data.frame(cbind(z , rep(0, nrow(z))))
DATA
index = knn.index(DATA,k=5)
print("INDEX")
index #indeks k-tego najbliższego sąsiada
knn.dist(DATA, k=nrow(z) -1) #odległości
D <- dist(DATA)
as.matrix(D)

X1         X2          X3           X4        X5
1 -1.7494745  0.14488813  0.005115225 0.8808498 0 
2  0.6480374  0.46986865  0.081739971 0.8629741 0 
3 -0.1665959 -0.04811958  0.719862533 0.9375037 0 
4  1.1913354  2.70230932 -0.786914891 1.2125327 0 
5 -1.7242960  0.61202877  0.638708246 0.9937969 0 
6  1.2421486 -0.64720409  0.910866685 1.1630290 0

[1] "INDEX"


[,1] [,2] [,3] [,4] [,5]
[1,] 5    3    2    6    4   
[2,] 3    6    1    5    4   
[3,] 2    6    5    1    4   
[4,] 2    3    6    5    1   
[5,] 1    3    2    6    4   
[6,] 2    3    1    5    4

[,1]      [,2]     [,3]     [,4]     [,5]    
[1,] 0.7956453 1.748379 2.420716 3.236855 3.990751
[2,] 1.1596095 1.542175 2.420716 2.444484 2.481072
[3,] 1.1596095 1.559105 1.694692 1.748379 3.428535
[4,] 2.4810716 3.428535 3.755893 3.866578 3.990751
[5,] 0.7956453 1.694692 2.444484 3.238545 3.866578
[6,] 1.5421750 1.559105 3.236855 3.238545 3.755893

1         2        3        4        5         6       
1 0.0000000 2.420716 1.748379 3.990751 0.7956453 3.236855
2 2.4207162 0.000000 1.159610 2.481072 2.4444843 1.542175
3 1.7483793 1.159610 0.000000 3.428535 1.6946919 1.559105
4 3.9907507 2.481072 3.428535 0.000000 3.8665780 3.755893
5 0.7956453 2.444484 1.694692 3.866578 0.0000000 3.238545
6 3.2368549 1.542175 1.559105 3.755893 3.2385445 0.000000

In [72]:
x <- matrix( c(3.3, 5.2, 7.3, 9.4, 4.5), 1,5)
x <- rbind(x, c(3.4, 3.7, 4.8, 5.4, 3.9))
x <- rbind(x, c(4.6, 7.2, 3.6, 4.5, 6.3))
x <- rbind(x, c(4.5, 3.6, 2.7, 3.4, 5.6))
o <- rep(0,nrow(x))
DATA <- data.frame(cbind(x , o))
DATA
D <- dist(DATA)
as.matrix(D)
library(FNN)
library(RANN)
NN <- get.knn(DATA,k=3)
NN


V1  V2  V3  V4  V5  o
1 3.3 5.2 7.3 9.4 4.5 0
2 3.4 3.7 4.8 5.4 3.9 0
3 4.6 7.2 3.6 4.5 6.3 0
4 4.5 3.6 2.7 3.4 5.6 0

1        2        3        4       
1 0.000000 4.986983 6.828616 7.897468
2 4.986983 0.000000 4.658326 3.538361
3 6.828616 4.658326 0.000000 3.934463
4 7.897468 3.538361 3.934463 0.000000

$nn.index
     [,1] [,2] [,3]
[1,]    2    3    4
[2,]    4    3    1
[3,]    4    2    1
[4,]    2    3    1

$nn.dist
         [,1]     [,2]     [,3]
[1,] 4.986983 6.828616 7.897468
[2,] 3.538361 4.658326 4.986983
[3,] 3.934463 4.658326 6.828616
[4,] 3.538361 3.934463 7.897468

In [16]:
index = knn.index(x,k=3)
index

[,1] [,2] [,3]
[1,] 2    3    4   
[2,] 4    3    1   
[3,] 4    2    1   
[4,] 2    3    1

In [90]:
T <- function(k,n,N ) {
  block1 <- NN$nn.index[1:n, ]
  block2 <- NN$nn.index [(n +1):N , ]
  i1 <- sum(block1[,1:k] <= n)  
  i2 <- sum(block2[,1:k] > n)
  return (1*sum(i1+i2)/(k*N))}

T3<- T(k=3,n=3,N=6)
T3
# NN

[1] 0.4444444

In [89]:
T3 = (1/ (3*6)) * (1+2+5)
T3

[1] 0.4444444

# Zad 4

In [48]:
x <- matrix(rnorm(mean(5), sd=sqrt(3)),nrow=5, ncol=5)
y <- matrix(rnorm(mean(5), sd=sqrt(3)), nrow=6, ncol=5)

In [49]:
z <- rbind(x,y)
o <- rep (0, nrow(z))
DATA <- data.frame(cbind (z,o))
NN <- get.knn(DATA,k=nrow(z)-1) # knn.dist (DATA, k = nrow (z) -1)
knn.index(DATA,k=nrow(z)-1) # 4a)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  5   3     9   10    7    6   11    8    4    2   
 [2,]  4   8    11    6    7   10    9    5    1    3   
 [3,]  1   5     9   10    7    8    6   11    4    2   
 [4,]  2   8     6   11    7   10    9    5    1    3   
 [5,]  1   3    10    7    6   11    8    9    4    2   
 [6,] 11   5     1    8    9    4    3    2   10    7   
 [7,]  5   1    10    9    4    3    2    6   11    8   
 [8,]  5   1     6   11   10    4    3    2    9    7   
 [9,]  5   1     7    6   11    4    3    2   10    8   
[10,]  5   1     7    8    4    3    2    9    6   11   
[11,] 11   5     1    8    9    4    3    2   10    7

In [68]:
#4b)
zad4b <- function(dane, k_neighbour,n,N){
    block1 <- NN$nn.index[1:n, ] # indeksy najbliższychvsąsiadów dla wektora X
    block2 <- NN$nn.index[(n+1):N, ] # indeksy najbliższych
    i1 <- sum(block1[,1:k_neighbour] <= n)  
    i2 <- sum(block2[,1:k_neighbour] > n)
  return (1*(i1+i2)/(k_neighbour*N)) }

list(zad4b(DATA, 1, 5, 11), zad4b(DATA, 3, 5, 11), zad4b(DATA, 5, 5, 11))

[[1]]
[1] 0.6363636

[[2]]
[1] 0.4242424

[[3]]
[1] 0.4363636

In [74]:
#c)
library(boot)
library(FNN)
library(RANN)
x <- matrix(rnorm(mean(5), sd=sqrt(3)),nrow=5, ncol=5)
y <- matrix(rnorm(mean(5), sd=sqrt(3)), nrow=6, ncol=5)
z <- rbind(x,y)

T <- function (z, ix,sizes, k_neigh) {
    n <- sizes[1]
    m <- sizes[2]
    N <- n + m
    z <- z[ix , ]
    o <- rep (0,nrow(z))
    DATA <-data.frame(cbind(z,o))
    NN <- get.knn(DATA,k=nrow(z)-1)
    block1<- NN$nn.index[1:5,1:k_neigh]
    block2<-NN$nn.index[6:11,1:k_neigh]
    i1 <- sum(block1<= n)
    i2 <- sum(block2 > n)
    return (( i1 + i2 ) / (k_neigh * N))}

M <- c(5, 6)
boot.obj<- boot(data=z, statistic=T, sim="permutation", R=999 , sizes=M, k_neigh=3)
boot.obj
p_value = mean(c(boot.obj$t, boot.obj$t0) >= boot.obj$t0)
p_value
boot.obj<- boot(data=z, statistic=T, sim="permutation", R=999 , sizes=M, k_neigh=5)
boot.obj
p_value = mean(c(boot.obj$t, boot.obj$t0) >= boot.obj$t0)
p_value
boot.obj<- boot(data=z, statistic=T, sim="permutation", R=999 , sizes=M, k_neigh=10)
boot.obj
p_value = mean(c(boot.obj$t, boot.obj$t0) >= boot.obj$t0)
p_value


DATA PERMUTATION


Call:
boot(data = z, statistic = T, R = 999, sim = "permutation", sizes = M, 
    k_neigh = 3)


Bootstrap Statistics :
     original      bias    std. error
t1* 0.5151515 -0.04368004  0.05363371

[1] 0.274


DATA PERMUTATION


Call:
boot(data = z, statistic = T, R = 999, sim = "permutation", sizes = M, 
    k_neigh = 5)


Bootstrap Statistics :
    original     bias    std. error
t1*      0.4 0.06400946  0.03179191

[1] 1


DATA PERMUTATION


Call:
boot(data = z, statistic = T, R = 999, sim = "permutation", sizes = M, 
    k_neigh = 10)


Bootstrap Statistics :
     original      bias    std. error
t1* 0.4545455 0.004995905 0.004525345

[1] 1

# zad 5

In [75]:
x <- matrix(rnorm(25),nrow=5, ncol=5)
y <- matrix(rnorm(30), nrow=6, ncol=5)
zad5 <- function(k_neighbour, x_elements){
    z <- rbind(x,y)
    o <- rep(0, nrow(z))
    DATA <- data.frame(cbind (z,o))
    NN <- get.knn(DATA,k=nrow(z)-1)
    knn.index(DATA,k=nrow(z)-1) # podpunkt a)
    block1 <- NN$nn.index[1:5,1:k_neighbour] # indeksy najbliższychvsąsiadów dla wektora X
    block2 <- NN$nn.index[6:11,1:k_neighbour] # indeksy najbliższych
    i1 <- sum (block1<=x_elements)
    i2 <- sum (block2>x_elements)
    return (list(i1, i2))}

T1 = (zad5(1, 5)[[1]]+zad5(1, 5)[[2]]) /(1*(6+5))
T3 =(zad5(3, 5)[[1]]+zad5(3, 5)[[2]])/(3*(6+5))
T5 =(zad5(5, 5)[[1]]+zad5(5, 5)[[2]]) /(5*(6+5))
list(T1,T3,T5)
boot.obj<- boot(data=z, statistic=T, sim="permutation", R=999, sizes=M, k_neigh=3)
boot.obj
p_value = mean(c(boot.obj$t, boot.obj$t0) >= boot.obj$t0)
p_value


[[1]]
[1] 0.3636364

[[2]]
[1] 0.3939394

[[3]]
[1] 0.4545455


DATA PERMUTATION


Call:
boot(data = z, statistic = T, R = 999, sim = "permutation", sizes = M, 
    k_neigh = 3)


Bootstrap Statistics :
     original      bias    std. error
t1* 0.5151515 -0.04604605  0.05134653

[1] 0.27

In [112]:
M <- c(5, 6)
katy=c(1,2,3,4,5,6,7,8,9,10)
for(i in 1:length(katy)){
  boot.obj <- boot (data = z, statistic =T ,sim = "permutation", R = 999, sizes = M,k_neigh=katy[i]) 
  p <- ((sum(boot.obj$t>=boot.obj$t0))+1)/1000  # p wartość 
  print(p) }

[1] 0.311
[1] 0.43
[1] 0.642
[1] 0.615
[1] 0.467
[1] 0.626
[1] 0.916
[1] 0.781
[1] 0.47
[1] 1
