In [4]:
#dane: #lambda - liczba całkowita; b i r nieznane
#a*r=b*k; lambda=r*(k-1)/(a-1)
#a - poziomy czynnika; b - bloki ; k - poziomy czynnika w bloku; r - replikacje poziomów czynnika
a=8 #poziom czynnika    a*r = b * k (k poziomów dla bloku)        r to ilość poziomów dla a (czynnika)
k=3

r=b=c()
estymacja=function(a,k){
  for (i in 1:100){    #jakie r 
  if(((k-1)*i)%%(a-1)==0){  # lambda wyliczone, jeżeli jest liczbą całkowitą
    if(((a*i)%%k)==0){   # a*r = N*a = b*k 
      r=append(r,i,after=length(r))
      be=(a*r)/k  
      b=append(b,be,after=length(b))}}}
  print(paste("a - poziomy czynnika:",a,"; b - bloki: ",b[1], "; r - replikacje: ",r[1], "; k - poziomy czynnika w bloku: ",k))
}
estymacja(a,k)

[1] "a - poziomy czynnika: 8 ; b - bloki:  56 ; r - replikacje:  21 ; k - poziomy czynnika w bloku:  3"


In [29]:
#1. Ho: Film nie miał wpływu na rodzaj wybieranych posiłków, H1: Film miał wpływ na rodzaj wybieranych posiłków
x = matrix(c(19, 48, 1, 32), byrow=TRUE, ncol=2, nrow=2)
colnames(x) <- c("Tak_po", "Nie_po") #PO
rownames(x) <- c("Tak_przed","Nie_przed") #PRZED
x = data.frame(x)
x

Tak_po Nie_po
Tak_przed 19     48    
Nie_przed  1     32

In [18]:
mcnemar.test(rbind(c(19,48),c(1,32)), correct =F) #p-value = 1.89e-11. Używam McNemara.


	McNemar's Chi-squared test

data:  rbind(c(19, 48), c(1, 32))
McNemar's chi-squared = 45.082, df = 1, p-value = 1.89e-11


In [43]:
x1 <- (1-48)**2/(1+48)
x1

[1] 45.08163

In [2]:
qchisq(0.95,df=1) #do + nieskonczonosc. W zakresie odrzucenia więc odrzucamy.

[1] 3.841459

In [3]:
#2
x = matrix(c(2, 5, 7, 11), byrow=TRUE, ncol=2, nrow=2)
colnames(x) <- c("Szwalnia1", "Szwalnia2") #PO
rownames(x) <- c("Wadliwe","Ok") #PRZED
x = data.frame(x)
sum(x) #ale jedna wartość poniżej 10 więc robię fishera.
x

[1] 25

Szwalnia1 Szwalnia2
Wadliwe 2          5       
Ok      7         11

In [3]:
x=matrix(c(2,5,7,11),2,2,byrow=T)

p <- function(dane) {
    n11 = dane[1,1]
    n12 = dane[1,2]
    n21 = dane[2,1]
    n22 = dane[2,2]
    N = sum(dane)
    x2 = (factorial(n11+n12)/(factorial(n11)*factorial(n12))*factorial(n21+n22)/(factorial(n21)*factorial(n22)))/(factorial(N)/(factorial(n11+n21)*factorial(N-(n11+n21))))
  return(x2) } # p(x)#[1] 0.3271229

r1 <- sum(x[1,]) #suma w wierszu 1
r2 <- sum(x[2,]) #suma w wierszu 2
c1 <- sum(x[,1]) #suma w kolumnie 1
c2 <- sum(x[,2]) #suma w kolumnie 2

minvalue <- min(r1, r2, c1, c2) #będę iterować po najmniejszej sumie z kolumn lub wierszy
index <- which.min(c(r1, r2, c1, c2)) #w którym punkcie zacząć od 0
p_wektor <- numeric(minvalue+1) #dlatego że zaczynam od 0
index

for (i in 0:minvalue) {
    if (index==1 | index==3){
  macierz <- rbind(c(i,r1-i),
                   c(c1-i,c2-r1+i))
  print(macierz)
  p_wektor[i+1] <- p(macierz) }
    if (index==2 | index==4){ #najmniejsza wartość dla wiersza 2 lub 4
  macierz <- rbind(c(c1-i,r1-c1+i),
                   c(i,r2-i))
  print(macierz)
  p_wektor[i+1] <- p(macierz)
    }}

sum(p_wektor[p_wektor <= p(x)]) #[1] 1, dlatego nie mamy podstaw od odrzucenia hipotezy zerowej, oznacza to: że obecność brakóW nie jest zależna od szwalni

[1] 1

     [,1] [,2]
[1,]    0    7
[2,]    9    9
     [,1] [,2]
[1,]    1    6
[2,]    8   10
     [,1] [,2]
[1,]    2    5
[2,]    7   11
     [,1] [,2]
[1,]    3    4
[2,]    6   12
     [,1] [,2]
[1,]    4    3
[2,]    5   13
     [,1] [,2]
[1,]    5    2
[2,]    4   14
     [,1] [,2]
[1,]    6    1
[2,]    3   15
     [,1] [,2]
[1,]    7    0
[2,]    2   16


[1] 1

In [16]:
#3
x = matrix(c(1,1,0,1,1,0,1,1,0,
             1,0,0,1,1,1,1,0,1,
             0,0,1,1,0,0,1,1,1,
             1,1,0,0,0,1,1,0,0,
             1,0,1,0,0,1,0,1,1,
             0,1,0,1,1,0,0,1,0,
             1,0,0,1,1,0,1,0,1), byrow=TRUE, ncol=9, nrow=7)
colnames(x) <- c("1","2","3","4", "5", "6", "7", "8", "9") #kolumna: koza
rownames(x) <- c("p","w","s","c","t", "o","n") #wiersz: dzień
x = data.frame(x)
x

X1 X2 X3 X4 X5 X6 X7 X8 X9
p 1  1  0  1  1  0  1  1  0 
w 1  0  0  1  1  1  1  0  1 
s 0  0  1  1  0  0  1  1  1 
c 1  1  0  0  0  1  1  0  0 
t 1  0  1  0  0  1  0  1  1 
o 0  1  0  1  1  0  0  1  0 
n 1  0  0  1  1  0  1  0  1

In [8]:
# data = c(1,1,0,1,1,0,1,1,0, 1,0,0,1,1,1,1,0,1,  0,0,1,1,0,0,1,1,1,  1,1,0,0,0,1,1,0,0, 1,0,1,0,0,1,0,1,1,   0,1,0,1,1,0,0,1,0, 1,0,0,1,1,0,1,0,1)
# lista = data.frame(data, rep(c("1","2","3","4", "5", "6", "7", "8", "9"),7), c(rep("pon", 9), rep("wt", 9), rep("sro", 9), rep("czw", 9), rep("pt", 9), rep("sob", 9), rep("niedz", 9)) )
# colnames(lista) <- c("Dane", "Koza", "Dzien")
# lista

In [53]:
k <- nrow(x)
R <- sum(colSums(x)**2)
C <- sum(rowSums(x)**2)
T <- sum(rowSums(x))

Q <- (k-1)* ((k*C)-(T**2))/(k*T-R)
cat("Q statystyka", Q, "\n") #1.68
p.val=pchisq(Q,df,lower=FALSE) 
cat("P value dla Q", p.val, "\n")
if (p.val>=0.05){cat("H0", "\n")}
if (p.val<0.05){cat("H0", "\n")}

df <- k-1
alfa <- 0.05
#Obustronny:
# cat("Obszar odrzucenia:", "(-inf ;", qchisq(alfa/2, k-1),"),(",  qchisq(1-alfa/2, k-1),"; +inf)", "\n") 
cat("Obszar odrzucenia: (",  qchisq(1-alfa, k-1),"; +inf)", "\n") 
#1.63. Nasze Q nie mieści się w zakresie odrzucenia. + nieskonczonosc.

Q statystyka 1.68 
P value dla Q 0.9466548 
H0 
Obszar odrzucenia: ( 12.59159 ; +inf) 


In [49]:
qchisq(1-alfa, k-1) 

[1] 12.59159

In [112]:
#4
x = matrix(c(30, 20, 40, 300), byrow=TRUE, ncol=2, nrow=2)
colnames(x) <- c("szczep", "brak")
rownames(x) <- c("zdrowe","chore") 
x = data.frame(x)
x

szczep brak
zdrowe 30      20 
chore  40     300

In [113]:
chisq.test(x,correct=FALSE) # p-value < 2.2e-16 Jest różnica.


	Pearson's Chi-squared test

data:  x
X-squared = 68.864, df = 1, p-value < 2.2e-16


In [114]:
OR =  300/20 / (40/30) #Ryzyko zachorowanie u nieszczepionych jest 11,25 x wyższa od ryzyka zachorowania u szczepionych
OR

[1] 11.25

In [55]:
13/13 / (1/11)

[1] 11

In [9]:
#Iloraz szans: szansa w jednej grupie/szansa w drugiej grupie. 
n11 = 30
n22 = 300
n21= 40
n12 = 20
OR = n11*n22/(n21*n12)  # (30*300/(40*20))
OR #Szansa na zachorowanie jest 11x wyższa wśród nieszczepionych

#Ryzyko względne:
RR = (40/(40+30)) / ((300)/(300+40))
RR #0.609.  Zachorowanie wśród szczepionych jest o 61% niższe niż u nie szczepionych.
RR =  ((300)/(300+40))  /  (40/(40+30)) 
RR

[1] 11.25

[1] 0.647619

[1] 1.544118

In [117]:
sum(x) # N = 390

[1] 390

In [118]:
#Statystyka testowa OR:
Z = log(OR) / (sqrt(1/n11 + 1/n12 + 1/n21 + 1/n22)) #7.24 powinno być
Z

[1] 7.243019

In [120]:
qnorm(0.95) #(do + nieskonczonosc, i -inf, -1.64)

[1] 1.644854

In [48]:
qnorm(1-0.95)

[1] -1.644854

In [ ]:
#Nasza próba wpada w obszar odrzucenia, czyli statystycznie jest różnica w szansie.