In [12]:
#1. kwadratu Youdena
x = matrix(c(2,9,0,14,
             6,5,5,3,
             1,9,0,7,
             8,8,10,4,
             7,6,11,10), byrow=TRUE, nrow = 5, ncol = 4)
colnames(x) <- c(1:4)
a = 5
b = 5
N = 20 #sumarycznie ile elementów
k = 4  #replikacje dla kolumny (b)
r=4 #replikacje w wierszu (dla a)
lambda = (r*(k-1))/(a-1) #4
Lac = matrix(c( "A", "B", "C", "D",
                "B", "A", "E", "C",
                "C", "D", "A", "E",
                "D", "E", "B", "A",
                "E", "C", "D", "B"), byrow=TRUE, nrow = 5, ncol = 4)

In [13]:
dane = cbind(as.list(Lac), as.list(x))
dane = data.frame(dane)
colnames(dane) = c("Lac", "Nr")
uniq = unique(sort(Lac))
y.x. <- numeric(length(uniq))
for (i in 1:length(uniq)) {    y.x.[i] = sum(unlist(subset(dane, Lac==uniq[i])$Nr)) }

In [14]:
idx_exist <- function(data, value){
    index = numeric(nrow(data))
    for (i in 1:nrow(data)){
        if (any(data[i,]==value)==TRUE){
           index[i] = i  } }
    return (index) }

In [15]:
sum_of_value_in_row <- function(data, Lac, row){
    index = numeric(ncol(data))
    myLetters <- LETTERS[1:26] 
    index = y.x.[match(Lac[row,], myLetters)]
    return (index) }

In [17]:
Lac

[,1] [,2] [,3] [,4]
[1,] A    B    C    D   
[2,] B    A    E    C   
[3,] C    D    A    E   
[4,] D    E    B    A   
[5,] E    C    D    B

In [11]:
Q1 =  y.x.[1] - 1/k*( sum(rowSums(x, na.rm=TRUE)[idx_exist(Lac,"A")], na.rm=T))
Q2 =  y.x.[2] - 1/k*( sum(rowSums(x, na.rm=TRUE)[idx_exist(Lac,"B")], na.rm=T))
Q3 =  y.x.[3] - 1/k*( sum(rowSums(x, na.rm=TRUE)[idx_exist(Lac,"C")], na.rm=T))
Q4 =  y.x.[4] - 1/k*( sum(rowSums(x, na.rm=TRUE)[idx_exist(Lac,"D")], na.rm=T))
Q5 =  y.x.[5] - 1/k*( sum(rowSums(x, na.rm=TRUE)[idx_exist(Lac,"E")], na.rm=T))
list(Q1,Q2,Q3,Q4,Q5) 
Q <- c(Q1,Q2,Q3,Q4,Q5)

SST = sum(x**2, na.rm=TRUE)   - sum(rowSums(x, na.rm=TRUE))**2/N
SScz = ((k*(sum(Q**2)))/(lambda*a)) #czynnika
SSwiersz =  sum(rowSums(x, na.rm=TRUE)**2)/k - sum(rowSums(x, na.rm=TRUE))**2/N #SSB
SSkolumna = sum(colSums(x, na.rm=TRUE)**2)/b - sum(rowSums(x, na.rm=TRUE))**2/N #SSs
SSE = SST-SScz-SSwiersz-SSkolumna

Q1_ = rowSums(x, na.rm=TRUE)[1] - 1/k*(  sum(sum_of_value_in_row(x, Lac, 1), na.rm=T))
Q2_ = rowSums(x, na.rm=TRUE)[2] - 1/k*(  sum(sum_of_value_in_row(x, Lac, 2), na.rm=T)) 
Q3_ = rowSums(x, na.rm=TRUE)[3] - 1/k*(  sum(sum_of_value_in_row(x, Lac, 3), na.rm=T))  
Q4_ = rowSums(x, na.rm=TRUE)[4] - 1/k*(  sum(sum_of_value_in_row(x, Lac, 4), na.rm=T))  
Q5_ = rowSums(x, na.rm=TRUE)[5] - 1/k*(  sum(sum_of_value_in_row(x, Lac, 5), na.rm=T)) 
list(Q1_, Q2_, Q3_, Q4_, Q5_)
SSwierszdop =  ((k*(sum(c(Q1_, Q2_, Q3_, Q4_, Q5_)**2)))/(lambda*a)) #dopełnienie

dfT <- N-1
dfcd <- a-1 #łac
dfW <- b-1 #wiersz 
dfK <- b-1-1
# dfE <- N-a-b+1
dfE <- dfT - dfcd - dfW - dfK

MScd = SScz/dfcd
MSW = SSwiersz/dfW
MSK = SSkolumna/(dfK) #położenie?
MSE = SSE/(dfE)
F0 = MScd/MSE
              
tabela <- rbind(c(SScz, dfcd, MScd, F0),
                c(SSwiersz, dfW, MSW, NA),
                c(SSwierszdop, dfW, NA, NA),
                c(SSkolumna, dfK, MSK, NA),
                c(SSE, dfE, MSE, NA),
                c(SST, dfT, NA, NA))
colnames(tabela) <- c("SumaKwadratów", "StopnieSwobody", "ŚredniKwadrat", "F")
rownames(tabela) <- c("cz. dopasowany", "wiersz(niedop)", "wiersz(dop)",  "kolumna", "bład", "całkowita")
tabela

[[1]]
[1] -11.75

[[2]]
[1] 8

[[3]]
[1] -13.75

[[4]]
[1] 15.5

[[5]]
[1] 2

[[1]]
[1] 0.5

[[2]]
[1] -1.75

[[3]]
[1] -5.5

[[4]]
[1] 1.25

[[5]]
[1] 5.5

SumaKwadratów StopnieSwobody ŚredniKwadrat F       
cz. dopasowany 169.43333      4             42.358333     14.69075
wiersz(niedop)  51.50000      4             12.875000           NA
wiersz(dop)     17.43333      4                    NA           NA
kolumna         31.75000      3             10.583333           NA
bład            23.06667      8              2.883333           NA
całkowita      275.75000     19                    NA           NA

In [51]:
qf(p=0.95, df1=(a-1), df2=dfE)

[1] 4.120312

In [ ]:
################### Czesciowo zrównoważone niekompletne bloki ###################
#Model statystyczny:
# yij = u + ti + bj + eij    gdzie:
# u - średnia
# ti - efekt i-tego poziomu czynnika
# bj - efekt j-tego bloku czynnika
# eij - błąd losowy

#Model Youdena:
#yijh = u + alfa(i) + tau(j) + Bh + e(ijh)
#u średnia
#alfa - efekt i tego bloku
#tauj - efekt j tego poziomu czynnika
#beta h - efekt h-tego położenia
# kolumna - położenie, blok - wiersz, 

In [4]:
#Zad2. Częściowo zrównoważone niekompletne bloki
x = matrix(c(1, NA, NA, 10, NA, 16,
            10, 24, 12, NA, NA, NA,
             20, NA, NA, 15, 19, NA,
             NA, 16, NA, 11, 10, NA,
             NA, 13, 17, NA, NA, 12,
             NA, NA, 9, NA, 10, 8), byrow=TRUE, nrow = 6, ncol = 6)
colnames(x) <- c(1:6)

In [2]:
x = matrix(c(1,NA, NA, 1, NA,1,
             1,NA, 1,  1, NA,NA,
             1, 1, NA,NA, 1, NA,
             NA,1,NA,1,1,   NA,
             NA, 1,1,NA,NA, 1,
            NA,NA, 1,NA,1,1), byrow=TRUE, nrow = 6, ncol = 6)
x

[,1] [,2] [,3] [,4] [,5] [,6]
[1,]  1   NA   NA    1   NA    1  
[2,]  1   NA    1    1   NA   NA  
[3,]  1    1   NA   NA    1   NA  
[4,] NA    1   NA    1    1   NA  
[5,] NA    1    1   NA   NA    1  
[6,] NA   NA    1   NA    1    1

In [5]:
tabela_wspolna <- function(dane) {
  a = nrow(dane)
  cat("a =",a,"\n")
  b = ncol(dane)
  cat("b =",b,"\n")
  k = length(na.omit(dane[,1]))
  cat("k =",k,"\n")
  r = length(na.omit(dane[1,]))
  cat("r =",r,"\n")  
  kombinacje <- rbind(c())
  for (i in 1:b) {
    kombinacje <- rbind(kombinacje,which(!is.na(dane[,i]))) }
  print(kombinacje)  
  lambda <- rbind(c())
  for (i in 1:(b-1)) { 
    for (j in (i+1):b) {
      licznik = 0
      for (x in 1:a) {
        if ((i %in% kombinacje[x,]) & (j %in% kombinacje[x,])) {
          licznik = licznik + 1  } }
      lambda <- rbind(lambda,c(i,j,licznik)) }  }
  tabela <- table(lambda[,3])
  print(tabela) 
  return(lambda)}

table = tabela_wspolna(x)
table = data.frame(table)
colnames(table) = c("pierwszy","drugi", "lambda")
table = table[with(table, order(lambda)),]

lambdy = unique(table$lambda)
lambdy 

for (i in 1:length(lambdy)){ #dla każdej lambdy
    print(i)
    size = length(lambdy)
    sub = subset(table, lambda==lambdy[i]) #podzbiór lambdy
    cat("Pjk dla lambdy = ",lambdy[i], "\n")
    pjk = matrix(c(rep(0, size), rep(0, size) ), byrow=TRUE, nrow=size, ncol=size)
    for (j in 1:length(lambdy)){ 
        for (k in 1:length(lambdy)){
        x1 = c(subset(table, pierwszy==sub[1,1] & lambda == lambdy[j])$drugi,subset(table, drugi==sub[1,1] & lambda == lambdy[j])$pierwszy) #stowarzyszenie dla lambdy[j]
        y1 = c(subset(table, pierwszy==sub[1,2] & lambda == lambdy[k])$drugi,subset(table, drugi==sub[1,2] & lambda == lambdy[k])$pierwszy) #stowarzyszenie dla lambdy[k]
        pjk[j,k] = length(intersect(x1,y1))     }}
print(pjk)
}

a = 6 
b = 6 
k = 3 
r = 3 
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    2    4    5
[3,]    2    5    6
[4,]    1    3    4
[5,]    3    4    6
[6,]    1    5    6

 0  1  2 
 1 10  4 


[1] 0 1 2

[1] 1
Pjk dla lambdy =  0 
     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    2
[3,]    0    2    0
[1] 2
Pjk dla lambdy =  1 
     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    2    1
[3,]    0    1    0
[1] 3
Pjk dla lambdy =  2 
     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    1    2    1
[3,]    0    0    0
